### ISSUE TITLE
Dates of birth and vaccination are overly precise

### ISSUE THREAD

**Issue by icanzilb** [philipptrenz/covidpass#10]
The dates on the imported pass display 00:00 as the time of birthday and vaccination. The dates should better display no time at all.

**Comment by icanzilb** [comment]
![Uploading 30BC6E23-5893-4FA0-B6DC-628596FC1E2B.jpeg…]()

**Comment by philipptrenz** [comment]
Hi Marlin, 

thanks for the input. I couldn't agree more. 
Following the JSON Schema specification, the only `date-time` string should be the _Date/Time of Sample Collection_ property on test certificates (see [here](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/main/DCC.combined-schema.json)). May I ask which country issued your certificate?

Nevertheless, I'll take a look for stripping the time off 👍🏼

**Comment by icanzilb** [comment]
Hi Philip, my certificate comes from Bulgaria 🇧🇬 I'll have a look at the json schema - I think I might have also other things to report 😀

**Comment by philipptrenz** [comment]
Hey @icanzilb 

I just pushed an update to the dev branch. Dates now get parsed, unified and localized by the selected language. If you like, you can try it out at https://dev.covidpass.eu It will get released within the next days 👍🏼

We're also currently working on providing more languages. If you're interested in helping out for a Bulgarian translation, feel free to reach out. It's not that much of a task 😉

**Comment by icanzilb** [comment]
Dates look better, thanks!

![FCF34E3F-2206-4D00-917B-31499FB61794](https://user-images.githubusercontent.com/633862/124735317-39fba600-df16-11eb-915b-2e8586f2aca8.jpeg)

**Comment by icanzilb** [comment]
@philipptrenz you can open a Bulgarian translation issue and assign it to me 👍🏼

**Comment by philipptrenz** [comment]
> @philipptrenz you can open a Bulgarian translation issue and assign it to me 👍🏼

Awesome! As we should do #11 beforehand to prevent duplication of translation work, I would postpone the translation for some days until #11 is done.
