### ISSUE TITLE
Trying to scan EU Digital covid certificate

### ISSUE THREAD

**Issue by spl26** [philipptrenz/covidpass#15]
While trying to scan my EU Digital covid certificate qr code. There is a red square on the qr code and nothing happens. So i can not have the pass. Am i doing something wrong?

Appreciate it your work and your great initiative. Thank you!

**Comment by philipptrenz** [comment]
Hey Spyros, 

sorry for that and thanks for reaching out! As the app runs locally in your browser, we don't have any information for troubleshooting. 

Have you already tried it on another browser or device?

I'd also check against the official certificate test data, if you let me know the issuing country of your pass. Possibly this leads me to some insights.

**Comment by spl26** [comment]
Hello Philipp,

Thanks a lot for the reply. Issuing country is Greece. Tried with safari and chrome on my iPhone. I do not have the iOS 15 beta just FYI.

Thanks again

**Comment by philipptrenz** [comment]
Hi Spyros, no worries 😉

I just tried the Greece test QR codes from [here](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/GR/2DCode/png) and they do work fine, as far as I can tell.

Can you please also try to scan them and report if it succeeds? Also, please check if the scanning of your certificate succeeds on another device. Thanks!

**Comment by spl26** [comment]
Hello Philipp,

Thanks a lot. I tried the test QR codes and there were fine. SO what i did was reissue my certificate from the goverment's website. That worked and now it worked. Only thing here is that the name is with Greek alphabet characters and not English. I show a similar issue in your Github

Thanks a lot.

**Comment by philipptrenz** [comment]
Awesome, glad we got it right!

Yeah, @icanzilb already stated that in #14. I will take a look 👍🏼
If you have any suggestions to this, feel free to comment in the other issue.
