### ISSUE TITLE
The button „add to apple wallet“ does not work

### ISSUE THREAD

**Issue by Bazooka2304** [philipptrenz/covidpass#16]
After scanning the QR-Code successfully the button „add to apple wallet“ does not upload it to the wallet. I’m using iPhone X with the lastest iOS version

**Comment by philipptrenz** [comment]
Hi @Bazooka2304, thanks for reaching out.

Hm, what exactly happens when you tap the badge?

**Comment by Bazooka2304** [comment]
Hi @philipptrenz,

thanks for your respone.

By using the Safari browser instead of Chrome it´s working perfectly!

Ticket can be closed. Thanks and have a good day.
