### ISSUE TITLE
Camera activation on Iphone

### ISSUE THREAD

**Issue by Sibbedes** [philipptrenz/covidpass#20]
Hi,
While this works in IPad, it seems not possible to give camera access on the iPhone for scanning..... ist this normal?
Thanks

**Comment by philipptrenz** [comment]
Hi @Sibbedes, thanks for reaching out!

Please check your Safari Camera settungs within your Settings app: `Safari` -> `SETTINGS FOR WEBSITE: Camera` -> `Ask` or `Allow`
