### ISSUE TITLE
Funktioniert nicht

### ISSUE THREAD

**Issue by Jeannette1973** [philipptrenz/covidpass#21]
Code lässt sich scannen, Button für Wallet funktioniert aber nicht. 
Gefühlt 100x probiert!!!

**Comment by philipptrenz** [comment]
Hi Jeannette,

bitte gib mir etwas mehr Informationen, damit wir sehen können wo das Problem liegt:

- Was funktioniert genau nicht, passiert im laufenden QR-Scanner nichts, lässt sich das "Hinzufügen zum Apple Wallet" nicht klicken oder etwas anderes?
- Kannst du den QR-Code mit der Corona-Warn oder CovPass-App einscannen?
- Welches Gerät und welchen Browser verwendest du? Das Herunterladen funktioniert nur zuverlässig auf iPhones und Macs im Safari-Browser, auf dem iPad funktioniert es leider gar nicht

**Comment by cr0** [comment]
Hi, bei uns hat es ebenfalls nur Safari unter iOS 14.6 funktioniert, nicht aber mit Chrome.

**Comment by timokoenig** [comment]
Kann ich bestätigen. Safari funktioniert. Chrome leider nicht

**Comment by philipptrenz** [comment]
Hey ihr, danke für eure Insights! Wir werden zeitnah einen Hinweis in der Webapp anbringen, dass das Herunterladen nur in Safari zuverlässig funktioniert
