### ISSUE TITLE
Cannot scan vaccination qr code

### ISSUE THREAD

**Issue by bondskin** [philipptrenz/covidpass#24]
I was able to add the qr code into CWA and Covpass. 

Your Browser app (on iPhone / Safari) does not recognize the qr code and cannot be added. 
There is no error message. 

It's the qr code I got to testify my 2nd and final vaccination

**Comment by philipptrenz** [comment]
Hey there, sorry for the late reply. We were notified, that downloading the pass only works reliably using Safari. If you didn't use safari, please try again with it and otherwise also let us know, so we can do further investigations.

**Comment by bondskin** [comment]
Hi @philipptrenz , I tried it again (with Safari, as before) now with iOS 14.7.1 and it worked instantly.
Many thanks for your reply.
