### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by friezzen** [philipptrenz/covidpass#26]
Kamera Zugriff erlauben? Wie?

**Comment by philipptrenz** [comment]
Hi @friezzen, sorry für die späte Rückmeldung.
In deinen iPhone Einstellungen kannst du unter `Safari` -> `Kamera` auf "Erlauben" oder "Fragen" stellen.
Wir arbeiten aktuell auch an einer FAQ-Seite, da nehmen wir diesen Punkt dann auch mit auf.
