### ISSUE TITLE
Remove Watermark

### ISSUE THREAD

**Issue by 10Meisterbaelle** [philipptrenz/covidpass#27]
There should be a a setting to remove the watermark.

**Comment by donatuswolf** [comment]
What do you mean by that? Can you describe the issue a little?

**Comment by 10Meisterbaelle** [comment]
I am talking about the "Generated by covidpass.eu":
[image: IMG_0217.jpg]

Am Fr., 13. Aug. 2021 um 17:57 Uhr schrieb Donatus Wolf <
***@***.***>:

**Comment by 10Meisterbaelle** [comment]
I am talking about the "Generated by covidpass.eu":
![IMG_0217](https://user-images.githubusercontent.com/45918080/129770376-846f41c3-a5f4-4c1f-bb12-752f4a9ed26c.jpg)

**Comment by philipptrenz** [comment]
What is the issue with this? Please explain your point.

**Comment by 10Meisterbaelle** [comment]
In my opinion, it ruins the look.

Philipp Trenz ***@***.***> schrieb am Do., 19. Aug. 2021,
16:51:
