### ISSUE TITLE
Provide upload functionality for digital certificate files (jpeg, png, pdf etc)

### ISSUE THREAD

**Issue by b3rit** [philipptrenz/covidpass#29]
There should be an option to scan the qr code from pictures. Because if i have the file on my phone i cannot scan it only with my camera. If it is already there, then it should be more easier to find because I don’t see it on my iPhone 11.

**Comment by philipptrenz** [comment]
Hey,

thanks for your suggestion. I see your point. We'll look into it, but this will take some time.

**Comment by philipptrenz** [comment]
I am closing this ticket for now, as there currently seems to be no real demand for this feature.
