### ISSUE TITLE
Problem with the size of QR code

### ISSUE THREAD

**Issue by puunukk** [philipptrenz/covidpass#32]
While people have different sized mobile phones I would highly recommend to make that QR code area/box much bigger as it is hard for people to read these codes from hands with other QR reading phone/device if they are so small. Just use the entire width, it would make much easier to check the CovidPass QR code (main purpose of the covid pass would be to check and validate).

**Comment by philipptrenz** [comment]
Hey there, thanks for your suggestion. And you're absolutely right, not the pass itself, but only the QR code is the valid certificate.

Unfortunately, the size of the QR code is defined by Apples framework, so we're not able to change that 😕

**Comment by philipptrenz** [comment]
Short update: I try to get in touch with some Apple engineers to discuss this issue, as it basically affects all QR codes with high data content. So far I have not been able to get an appointment for a developer session.

**Comment by cyprien3** [comment]
I don't know if it's any help, but I noticed that when scanning german recovery certificate and german vaccine certificate the app [pass4wallet](https://apps.apple.com/de/app/pass4wallet-store-cards/id1423106610) creates cards with different size of QR codes. The QR codes for recovery certificates are a bit larger, Not a huge difference, but definitely helpful for some phone's cameras in my tests.

![pass4waller - certs](https://user-images.githubusercontent.com/93480516/151695540-76b41679-b37d-4141-9e62-61a58e24be5d.png)

**Comment by philipptrenz** [comment]
Hi @cyprien3, thanks for your helpful notice. I'll look into it as soon as possible. But as this is a spare time project, it's hard to find the time. I hope you understand.

**Comment by cyprien3** [comment]
@philipptrenz no worries, this app is already amazing. Maybe it will resolve it self all alone, I see in iOS 15.4 that the QR code for the Covid pass is now even bigger:

![Untitled 3](https://user-images.githubusercontent.com/93480516/157419156-95ee285f-84da-487c-bd3e-737a1d748683.png)

**Comment by donatuswolf** [comment]
Yes, Apple made their own version since they realised the problem of the size. Sadly they didn't update the generic passes. So still no way for us to create a larger version 😕
