### ISSUE TITLE
improve disclaimer/instructions for iOS users

### ISSUE THREAD

**Issue by ttoomema** [philipptrenz/covidpass#33]
improve instructions for iOS users, that Safari shall be used for scanning QR-code. 
using Chrome does not let the integration happen between Wallet => pass will not be installed there.

**Comment by philipptrenz** [comment]
Hey @ttoomema, we're aware of this issue and on it. An update with an appropriate hint will soon be available.

**Comment by donatuswolf** [comment]
Workin' on it. Will look like this very soon
![image](https://user-images.githubusercontent.com/13907900/131710809-d13e5f08-c188-4573-99cb-bdbdf8a41021.png)

**Comment by janbrasna** [comment]
@philipptrenz TBH this is not completely true. I can use Safari on desktop, or, even any browser on desktop… and download the resulting .pkpass file, and open that from desktop (to save to my Wallets via iCloud) — I even prefer this way (to have a copy of the pass saved locally for later use). You then click the .pkpass to preview it and act upon it:

![Screen Shot 2021-10-11 at 01 36 37](https://user-images.githubusercontent.com/1784648/136720080-92a3765c-ded8-4004-830e-58d78b3ba889.png)

![Screen Shot 2021-10-11 at 03 11 51](https://user-images.githubusercontent.com/1784648/136720762-6d55043b-de0c-4ec1-ad20-c3803d98a7ec.png)

So the banner should really be only displayed when on mobile, or, rather reworded for taking this (indirect) desktop route into consideration.

**Comment by philipptrenz** [comment]
@janbrasna Thanks for your feedback! And you're right and we are aware of that. But as the pass contains sensitive personal data, we decided to only promote this one clear way of using it. Downloading the pass on a desktop device, where it cannot be used sensibly, opens up risks of a non-secure transfer of the pass.

**Comment by janbrasna** [comment]
@philipptrenz Ah okay, gotcha! That's a good choice.

The use case for "downloading" bare .pkpass files might be for users for other systems, e.g. Android has some apps for storing & display of Wallet's .pkpass files even for that other platform — and that means downloading the resulting pass file. But I guess those "power users" needing such route are aware of the way to make us of their specific needs/flows. 👍
