### ISSUE TITLE
Educate the user about device privacy settings

### ISSUE THREAD

**Issue by ahlstronomi** [philipptrenz/covidpass#35]
Since the pass contains sensitive information, the user might want to improve their personal privacy by preventing the access to Apple wallet from a locked screen.

At least with Face ID equipped devices it can be done from "Settings -> Face ID & Passcode -> Allow access when locked: Wallet"

**Comment by philipptrenz** [comment]
Hi @ahlstronomi, exactly what we say on the screen with the download badge, right? 😉 
Can I close this issue?

![Bildschirmfoto 2021-08-25 um 08 50 42](https://user-images.githubusercontent.com/11627598/130740804-8528d064-2b80-4924-9d9c-62cb6eaa8ba7.png)

**Comment by ahlstronomi** [comment]
Glad to see you have taken this into account! Before closing the issue though, please consider improving the badge layout so I will be the last clueless user who completely missed that information. To help you out a bit here's a suggestion for the layout. 


https://user-images.githubusercontent.com/22050325/130746069-7f48fddb-d65b-4bf8-bbef-ca8533613457.mov

**Comment by philipptrenz** [comment]
Awesome, thanks for that constructive feedback! I'll keep the issue open for now and hand your suggestions over to our designer @donatuswolf 👍🏼

**Comment by donatuswolf** [comment]
@ahlstronomi Thank you so much for your suggestion, here's how we want to implement the security info:
<img width="287" alt="Frame 16" src="https://user-images.githubusercontent.com/13907900/131210524-d1cb075e-9c98-4d34-a178-eda778ae3057.png">

(also added it to your figma file for comparison)
