### ISSUE TITLE
Off-by-one error in dates if west of UTC

### ISSUE THREAD

**Issue by ebroder** [philipptrenz/covidpass#39]
I noticed that my COVID pass had an off-by-one error on all of the dates (both my birthdate and my vaccination dates). I think this is because `new Date("datestring")` interprets the argument in UTC, but returns a Date object in local time. This is problematic if, say, you live in the western hemisphere, and midnight in UTC is the day before in local time:

```js
> const d = new Date("1980-01-01")
Mon Dec 31 1979 16:00:00 GMT-0800 (Pacific Standard Time)
> const locale = window.$nuxt.$i18n.locale
'en'
> const localeDateString = d.toLocaleDateString(locale, {
  year: 'numeric', month: 'numeric', day: 'numeric'
});
'12/31/1979'
```

This causes `formatDateString` in `payload.js` to return the wrong date.

Somewhat annoyingly, MDN [calls out this failure mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#:~:text=Parsing%20of%20date%20strings%20with%20the%20Date%20constructor%20(and%20Date.parse()%2C%20which%20works%20the%20same%20way)%20is%20strongly%20discouraged) but doesn't have any alternative recommendation, so I'm not really clear what the right way to do this is.

**Comment by ebroder** [comment]
(Also, since this will require editing `formatDateString`, it would be kind of nice if I ended up with European-style date formats; as it is, I end up with "MM/DD/YYYY")

**Comment by philipptrenz** [comment]
Hi @ebroder thanks for reporting this issue, I'll look into it!

**Comment by ebroder** [comment]
Ah, interesting. Right now, the date is just being passed into PassKit as a string (c.f. https://github.com/philipptrenz/covidpass/commit/9d9dcaedb7e562703ad2921845ecc496d3ce9dd1), so I don't think any of the date formatting in PassKit itself is firing.

But there are a bunch of parameters in `PassFieldContent` that control how ISO 8601 dates are formatted in the pass. Maybe instead of formatting the date into a string, you could go back to passing in the raw ISO 8601 date from the EUDCC and set, like, `dateStyle: 'PKDateStyleLong', timeStyle: 'PKDateStyleNone', ignoresTimeZone: true` or something.

**Comment by philipptrenz** [comment]
Thank you all for your inputs! It was a tough one, but I think I found a valid and clean solution.

I checked against https://github.com/eu-digital-green-certificates/dgc-testdata and there are some inconsistencies within the issued certificates. Also, Apple does not recognize all ISO8601 dates, esp. non date-only ones. 

I deployed the changes to https://dev.covidpass.eu, can you guys please check if the issue is resolved and everything is working properly?

**Comment by ebroder** [comment]
Looks good to me! For reference, the date fields on my (German) EU DCC appear to be formatted `"2021-11-14"` (no time), and they're displayed in the resulting PassKit pass as "Nov 14, 2021"

Thanks for working on this 🙂
