### ISSUE TITLE
spacing in arabic

### ISSUE THREAD

**Issue by donatuswolf** [philipptrenz/covidpass#40]
Spacing between icons/checkmarks and text and the alignment between the three USPs is not correct

![IMG_0931](https://user-images.githubusercontent.com/13907900/135822006-c024627c-1aab-4fc8-abdf-04f010c93dbb.PNG)

**Comment by philipptrenz** [comment]
Is related to: https://github.com/tailwindlabs/tailwindcss/issues/2017

**Comment by donatuswolf** [comment]
closing since it seems to be not used and so irrelevant to fix
