### ISSUE TITLE
mobile width in Russian

### ISSUE THREAD

**Issue by donatuswolf** [philipptrenz/covidpass#41]
The USP labels make the Russian version wider than the screen width, they should break into two lines.

![IMG_51A258297A72-1](https://user-images.githubusercontent.com/13907900/136237437-392b84fd-2d02-4463-8729-ed5f0157d24b.jpeg)

**Comment by philipptrenz** [comment]
As these are single words, they cannot break into two lines automatically. I tried to do it via css using `hyphens: auto;`, but that seems not to work for Russian. 

@donatuswolf Best option is to use `<wbr>` or `&shy;` within the translation file to force the break. But therefore we need a native speaker to place it correctly. Can you take care of that?
