### ISSUE TITLE
Date of birth off-by-one

### ISSUE THREAD

**Issue by deni** [philipptrenz/covidpass#45]
Was thinking of making this. Thank you for the work, very appreciated.

Importing my Danish certificate results in my wallet pass showing my date of birth of-by-one (-1).

**Comment by philipptrenz** [comment]
Hey @deni, thanks!
The issue was already reported in #39. 
I'll try to fix this asap, otherwise you're very welcome to look into it and create a PR.
I'll close this issue to concentrate the discussion to #39.
