### ISSUE TITLE
Camera didn’t see

### ISSUE THREAD

**Issue by mark-galich** [philipptrenz/covidpass#47]
Camera - violet ekran

**Comment by philipptrenz** [comment]
Hi @mark-galich thanks for reporting! 
I upgraded a dependency, can you please check at https://dev.covidpass.eu if the issue is still there?

**Comment by dannythunder** [comment]
My camera went grey.

Had it pointing towards the keyboard, saw a quick flash of it, then grey.
Two times.

Third time I pointed the camera towards the qr code, and it worked, tracked the qr and I was able to add it to the wallet
