### ISSUE TITLE
I cant Scan a testresult from EcoCare

### ISSUE THREAD

**Issue by Sebastian-Voigt** [philipptrenz/covidpass#54]
I cant Scan a testresult from EcoCare

![8AABC87F-F41C-4DF9-A4B0-855624985AD6](https://user-images.githubusercontent.com/66883897/145675370-9c5e4666-bb4f-465d-a290-30abfe71b0ac.jpeg)

allways the Same Issue.

**Comment by donatuswolf** [comment]
looks like the code you tried to scan is not an official one. Maybe it's a a check in code or an other service specific one. Couldn't reproduce the issue
