### ISSUE TITLE
Problems with covidpass scan for wallet creation 

### ISSUE THREAD

**Issue by Michael120460** [philipptrenz/covidpass#55]
**Describe the bug**

Problems with corvidpass scan for wallet creation 

**To Reproduce**

It wasn’t possible to scan the CovPass 

**Expected behavior**
Full functionality like shown in demo video to create a wallet CovPass 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone13]
 - OS: [iOS15.11]
 - Browser [iPhone safari]
 - Version [??]

**Comment by donatuswolf** [comment]
unfortunately this issue is not specific enough to solve it properly
