### ISSUE TITLE
Usability improvement

### ISSUE THREAD

**Issue by janstieler** [philipptrenz/covidpass#59]
**Is your feature request related to a problem? Please describe.**
I have no printed version of my QR codes by hand. So I can't use your app to make a foto of it.

**Describe the solution you'd like**
Upload a screenshot of my vaccinated WR code from the Corona Warn app.

**Comment by philipptrenz** [comment]
Hi @janstieler thanks for your feedback. We're already on it, see on #48. I'll close your issue to streamline the discussion.
