### ISSUE TITLE
Bug/Feature Request: Making the QR code larger

### ISSUE THREAD

**Issue by krzemian** [philipptrenz/covidpass#63]
**Is your feature request related to a problem? Please describe.**
Today I had my first attempt at getting the passport scanned. Done at a reception desk via a smartphone. Several attempts failed, however, as the QR was too small, including all glares etc. it turned out to be unreadable. I feel like this may be a common problem in places where they scan your codes via a relatively cheap/old smartphone.

**Describe the solution you'd like**
Larger QR code

**Describe alternatives you've considered**
I used the screenshot of my certificate that I had for backup

**Comment by donatuswolf** [comment]
We already discussed that in #32 closing this one now
